name:                redis-eff
version:             0.1.0.0
github:              "smb374/redis-eff"
license:             BSD-3-Clause
author:              "Po-Yeh Chen"
maintainer:          "poyehchen@cs.nycu.edu.tw"
copyright:           "2024 Po-Yeh Chen"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smb374/redis-eff#readme>

dependencies:
# Base
- base >= 4.7 && < 5
# Effectful
- effectful
- effectful-core
- effectful-plugin
- effectful-th
# Others
- ansi-terminal
- attoparsec
- bytestring
- containers
- exceptions
- fast-logger
- hashable
- network
- optparse-applicative
- random
- text
- unix-time
- unliftio
- unordered-containers
- vector

ghc-options:
# Effectful
- -O2
- -fplugin=Effectful.Plugin
# Wranings
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

library:
  source-dirs: src

executables:
  run-redis-eff:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redis-eff

tests:
  redis-eff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redis-eff
